### PR TITLE
Update to latest openxrs

### PR DESCRIPTION
**Pull request by Manishearth**
Uses my fork until https://github.com/Ralith/openxrs/pull/33 lands

Yet to be tested

### CODE REVIEW

**Comment by asajeffrey** [comment]
LGTM. Should we wait on landing this until https://github.com/Ralith/openxrs/pull/33 merges?

**Comment by Manishearth** [comment]
Yes, also I need to test this

**Comment by Manishearth** [comment]
Tested, works great. I updated it to point to a new branch on our fork, but once my PR lands and we have a release we can be back on mainline!

**Comment by Manishearth** [comment]
Oh, right, master isn't building

**Comment by Manishearth** [comment]
@bors-servo r=asajeffrey

Some of the secondary stuff was removed in the layers PR, @asajeffrey are you planning on reintroducing it?

**Pull request merged**
