### PR TITLE
Always call wait_for_animation_frame after rendering

### PR DESCRIPTION
**Pull request by Manishearth**
Potential fix for #96

I need to profile things first to see if this improves anything.

cc @asajeffrey

### CODE REVIEW

**Comment by Manishearth** [comment]
This brings the delay from 12ms down to around 3ms.

r? @asajeffrey

**Comment by Manishearth** [comment]
This brings the delay from 12ms down to around 3ms.

r? @asajeffrey

**Comment by asajeffrey** [comment]
I don't understand how this change can make that much difference! But r=me anyway, even if I am very very confused.

**Comment by Manishearth** [comment]
@bors-servo r=asajeffrey

i am confused too, I'm suspecting it's just IPC but can't be sure

**Pull request merged**
