### PR TITLE
Bump bindgen

### PR DESCRIPTION
**Pull request by nox**

### CODE REVIEW

**Comment by Manishearth** [comment]
cc @asajeffrey who has access to the headers to regenerate stuff with

**Comment by nox** [comment]
Oh, bindgen isn't actually used at build-time?

**Comment by Manishearth** [comment]
Oh, it might be.

**Comment by nox** [comment]
Well if it isn't, it has no business being a build dependency then, hah.

**Comment by asajeffrey** [comment]
Bindgen was used by the magicleap back end, but that has bitrotted. At this point we might want to bite the bullet and remove magicleap, perhaps with a "if anyone wants to take this over" comment?

**Pull request merged**
