### PR TITLE
Update surfman to latest commit

### PR DESCRIPTION
**Pull request by wusyong**
This PR is required before servo also update surfman dependency.

### CODE REVIEW

**Review by sagudev — APPROVED** [review]

**Comment by sagudev** [comment]
Hopefully you can merge this, because I can't:
> Merging is blocked
    You're not authorized to push to this branch

**Comment by wusyong** [comment]
welp I can't either. Let's just enjoy New Year Eve then. 😅

**Comment by sagudev** [comment]
🥂

**Comment by wusyong** [comment]
@mrobinson thanks and happy new year!

**Comment by mrobinson** [comment]
> @mrobinson thanks and happy new year!

Happy new year to you as well!

**Comment by jdm** [comment]
I have fixed the branch merge protections to allow the maintainers team to push to the main branch.

**Pull request merged**
